import { z } from 'zod';
import { AiReviewCommentSchema, PRReviewRequestSchema } from '../schemas';

/**
 * Represents a single review comment generated by the AI.
 */
export type AiReviewComment = z.infer<typeof AiReviewCommentSchema>;

/**
 * Represents the request payload for initiating a PR review.
 */
export type PRReviewRequest = z.infer<typeof PRReviewRequestSchema>;

/**
 * Represents a record of a recently performed review.
 */
export interface RecentReview {
  /** Unique identifier for the review, typically in the format "owner/repo#pullNumber". */
  id: string;
  /** The owner of the repository. */
  owner: string;
  /** The name of the repository. */
  repo: string;
  /** The pull request number. */
  pullNumber: number;
  /** The raw input string (e.g., URL) used to initiate the review. */
  inputString: string;
  /** Unix timestamp (in milliseconds) of when the review was performed. */
  timestamp: number;
}
